AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TrueTestify Backend API on AWS Lambda with RDS

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Deployment stage
  DatabaseHost:
    Type: String
    Description: RDS Database Host (Endpoint)
  DatabasePort:
    Type: Number
    Default: 5432
    Description: RDS Database Port
  DatabaseName:
    Type: String
    Default: truetestify
    Description: Database Name
  DatabaseUsername:
    Type: String
    Description: Database Username
  DatabasePassword:
    Type: String
    NoEcho: true
    Description: Database Password
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where RDS is located
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet IDs for Lambda (at least 2)
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for Lambda to access RDS
  S3Bucket:
    Type: String
    Description: S3 Bucket Name for file storage

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 1024
    Environment:
      Variables:
        NODE_ENV: production
        AWS_REGION: !Ref AWS::Region
        DB_HOST: !Ref DatabaseHost
        DB_PORT: !Ref DatabasePort
        DB_NAME: !Ref DatabaseName
        DB_USERNAME: !Ref DatabaseUsername
        DB_PASSWORD: !Ref DatabasePassword

Resources:
  # Lambda Function
  TruetestifyApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub truetestify-api-${Stage}
      CodeUri: dist/
      Handler: lambda.handler
      Runtime: nodejs20.x
      Timeout: 30
      MemorySize: 1024
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds: !Ref SubnetIds
      Environment:
        Variables:
          NODE_ENV: production
          AWS_REGION: !Ref AWS::Region
          DB_HOST: !Ref DatabaseHost
          DB_PORT: !Ref DatabasePort
          DB_NAME: !Ref DatabaseName
          DB_USERNAME: !Ref DatabaseUsername
          DB_PASSWORD: !Ref DatabasePassword
          AUTH0_DOMAIN: !Ref Auth0Domain
          AUTH0_AUDIENCE: !Ref Auth0Audience
          AWS_S3_BUCKET: !Ref S3Bucket
          STRIPE_SECRET_KEY: !Ref StripeSecretKey
          STRIPE_WEBHOOK_SECRET: !Ref StripeWebhookSecret
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:ListBucket
              Resource:
                - !Sub arn:aws:s3:::${S3Bucket}
                - !Sub arn:aws:s3:::${S3Bucket}/*
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref TruetestifyApi
        ApiGatewayRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref TruetestifyApi

  # API Gateway
  TruetestifyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub truetestify-api-${Stage}
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      DefinitionBody:
        swagger: 2.0
        'x-amazon-apigateway-binary-media-types':
          - 'multipart/form-data'
          - 'image/jpeg'
          - 'image/png'
          - 'application/octet-stream'
        info:
          version: '1.0'
          title: !Sub truetestify-api-${Stage}
        paths: {}
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub truetestify-lambda-role-${Stage}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${S3Bucket}
                  - !Sub arn:aws:s3:::${S3Bucket}/*

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${TruetestifyApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}
  LambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref TruetestifyApiFunction
